# -*- coding: utf-8 -*-
"""Cross_Validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hK__1IA_jlhjPSwLW3wL8KNHwunaEK4j
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt

# Importing the models

from sklearn.svm import SVC

from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

df = pd.read_csv("/content/sample_data/heart.csv")
df.head
X = df.drop(columns = "target", axis = 1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, stratify = y, random_state=42) ## Startify ensure same number of data in both x & y

models = [LogisticRegression(), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

def compare_model():
    for model in models:
        model.fit(X_train, y_train) # Indented this line
        y_pred = model.predict(X_test) # Indented this line
        accuracy = accuracy_score(y_test, y_pred) # Indented this line
        print("Accuracy of the", model, "= ", accuracy) # Indented this line and corrected the print statement

compare_model()

"""# **CV_Linear Regression**"""

cv_score_lr = cross_val_score(LogisticRegression(max_iter = 1000), X, y, cv=5)
print(cv_score_lr)
mean = np.mean(cv_score_lr)
print(mean)

## Alternatively,
mean = sum(cv_score_lr )/ len(cv_score_lr)
print("mean:",round(mean))


# cv_score_KNC = cross_val_score(KNC, X, y, cv=5)
# cv_score_RFC = cross_val_score(RFC, X, y, cv=5)

"""#**CV_SVM Classifier**"""

cross_Val_score_svm = cross_val_score(SVC(kernel='linear'), X, y, cv=5)
print(cross_Val_score_svm)
mean = sum(cross_Val_score_svm)/len(cross_Val_score_svm)
## Alternatively,
mean = np.mean(cross_Val_score_svm)
print("mean:", round(mean))

"""## **CV_KNeighbors Classifier**"""

cross_Val_score_svm = cross_val_score(KNeighborsClassifier(), X, y, cv=5)
print(cross_Val_score_svm)
mean = sum(cross_Val_score_svm)/len(cross_Val_score_svm)
## Alternatively,
mean = np.mean(cross_Val_score_svm)
print("mean:", round(mean))

"""# **CV_RandomForestClassifier()**"""

cross_Val_score_svm = cross_val_score(RandomForestClassifier(), X, y, cv=5)
print(cross_Val_score_svm)
mean = sum(cross_Val_score_svm)/len(cross_Val_score_svm)
## Alternatively,
mean = np.mean(cross_Val_score_svm)
print("mean:", round(mean))

"""# **Comparing the Model**"""

def compare_model():
    for model in models:
        cross_val_score_model = cross_val_score(model, X, y, cv=5) # Indented these lines and corrected the model input
        print(cross_val_score_model) # Indented these lines
        mean = np.mean(cross_val_score_model) # Indented these lines
        print(mean) # Indented these lines
        print("mean:",round(mean)) # Indented these lines

        print("model_name:", model)
        print("cross_validation_score:",cross_val_score_model)
        print("mean:",round(mean))

compare_model()

